#!/usr/bin/env python

"""game_constants.py: contains all of the game_constants that need to be used globally"""

__author__      = "Scott Munro"
__copyright__   = "Copyright 2015"

"""
SIZES
"""
# ENVIRONMENT
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_DIAGONAL = ((WINDOW_WIDTH ** 2) + (WINDOW_HEIGHT ** 2)) ** (0.5)

# PLAYER
PLAYER_WIDTH = 20
PLAYER_HEIGHT = 20

# BASIC ENEMY CONSTANTS
BASIC_ENEMY_WIDTH = 20
BASIC_ENEMY_HEIGHT = 20

# BULLET
PISTOL_BULLET_WIDTH = 10
PISTOL_BULLET_HEIGHT = 10

# OBSTACLE CONSTANTS
BOUNDING_WALL_THICKNESS = 20

#ITEM CONSTANTS
PISTOL_AMMO_WIDTH = 10
PISTOL_AMMO_HEIGHT = 10

"""
TIME
"""
# ENVIRONMENT
CLOCK_FPS = 60

# GENERATOR CONSTANTS
ENEMY_PERIOD = 150
AMMO_PERIOD = 1000

"""
QUANTITIES
"""
# PLAYER
PLAYER_VELOCITY = 3

# BASIC ENEMY
BASIC_ENEMY_VELOCITY = 1

# WEAPON
PISTOL_CLIP_CAPACITY = 6

# BULLET
PISTOL_BULLET_VELOCITY = 20

"""
MISC VALUES
"""
# COLORS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

# WEAPON
PISTOL_KEY = 1

