#!/usr/bin/env python

"""game_constants.py: contains all of the game_constants that need to be used globally"""

__author__      = "Scott Munro"
__copyright__   = "Copyright 2015"

# ENVIRONMENT CONSTANTS
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
CLOCK_FPS = 60

# PLAYER_CONSTANTS
PLAYER_WIDTH = 20
PLAYER_HEIGHT = 20
PLAYER_VELOCITY = 3

# ENEMY CONSTANTS
ENEMY_PERIOD = 100

# BASIC ENEMY CONSTANTS
BASIC_ENEMY_WIDTH = 20
BASIC_ENEMY_HEIGHT = 20
BASIC_ENEMY_VELOCITY = 1

# COLORS
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# WEAPON CONSTANTS
PISTOL_KEY = 1

# BULLET CONSTANTS
PISTOL_VELOCITY = 10
PISTOL_BULLET_WIDTH = 10
PISTOL_BULLET_HEIGHT = 10
